export type AccountRecord = {
  id: string;
  email: string;
  display_name: string;
  notes: string;
  aliases: string;
  username: string;
  password_cipher: string;
  incoming_protocol: "imap" | "pop3";
  auth_mode: "password" | "app_password";
  imap_host: string;
  imap_port: number;
  imap_secure: number;
  smtp_host: string;
  smtp_port: number;
  smtp_secure: number;
  sync_status: string;
  last_sync_at: string | null;
  sync_cursor_uid: number;
  sync_uid_validity: string | null;
  created_at: string;
  updated_at: string;
};

export type MessageRecord = {
  id: string;
  account_id: string;
  folder: string;
  uid: number | null;
  message_id: string | null;
  in_reply_to: string | null;
  reference_ids: string;
  subject: string;
  sender_name: string | null;
  sender_email: string | null;
  recipients: string;
  snippet: string;
  text_body: string;
  html_body: string | null;
  sent_at: string | null;
  flags: string;
  remote_mailbox: string | null;
  remote_uid_validity: string | null;
  remote_state: string;
  local_state_overrides: string;
  is_read: number;
  is_starred: number;
  is_archived: number;
  is_deleted: number;
  archived_at: string | null;
  deleted_at: string | null;
  created_at: string;
  updated_at: string;
};
